force_keyboard_focus = true    # forces keyboard forcus to stay in Walker
selection_wrap = true          # wrap list if at bottom or top
theme = "jvdb"               # theme to use
disable_mouse = false           # disable mouse (on input and list only)
hide_action_hints = true


[placeholders]
"default" = { input = "Search", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[keybinds]
quick_activate = []

[providers]
max_results = 256
default = [
  "desktopapplications",
  "websearch",
] # providers to be queried by default

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = "."
provider = "files"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

